ASM-WCF/Models/StudentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ASM_WCF.Models
{
    public class StudentViewModel
    {
        [ScaffoldColumn(false)]
        public int Id { get; set; }
        //[Required(ErrorMessage = "MSSV không thể để trống")]
        [Display(Name ="MSSV")]
        public string RolleNumber { get; set; }

        //[Required(ErrorMessage = "Tên sinh viên không thể để trống")]
        [Display(Name = "Tên Sinh Viên")]
        public string Name { get; set; }

        //[Required(ErrorMessage = "Ngày sinh không thể bỏ trống")]
        [Display(Name = "Ngày sinh")]
        public DateTime Birthday { get; set; }


        [Display(Name = "Giới tính")]
        public StudentGenre Genre { get; set; }

        //[Required(ErrorMessage = "Hãy nhập email")]
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage ="Email không hợp lệ vd: sinhvien@gmail.com")]
        public string Email { get; set; }

        //[Required(ErrorMessage = "Mục này không được để trống")]
        [Display(Name = "Giới thiệu bản thân")]
        public string Introduction { get; set; }
   
        public enum StudentGenre
        {
            [Display(Name = "Nữ")]
            Female = 0,
            [Display(Name = "Nam")]
            Male = 1
        }
    }
}

ASM-WCF/Controllers/HomeController.cs
using ASM_WCF.ServiceReference1;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASM_WCF.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public string About()
        {
            return "hello";


        }

        public ActionResult Contact()
        {
            ServiceClient client = new ServiceClient();

            // Use the 'client' variable to call operations on the service.
            var res = client.CreateStudent(new Student
            {
                Name = "Huy",
                Rollnumber ="A001",
                Birthday = DateTime.Now,
                Introduction = "hello",
                Genre = 1,
                Email = "hello@gamil.com"
                

            });
            // Always close the client.
            client.Close();

            return View();
        }
    }
}

ASM-WCF/Controllers/StudentController.cs
using ASM_WCF.Helpers;
using ASM_WCF.Models;
using ASM_WCF.ServiceReference1;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASM_WCF.Controllers
{
    public class StudentController : Controller
    {

        // GET: Student
        public StudentController()
        {

        }
        public ActionResult Index()
        {
            List<StudentViewModel> listStudent = new List<StudentViewModel>();
            ServiceClient serviceClient = new ServiceClient();
            var inDbListStd = serviceClient.GetListStudents();
            //convert to view model
            foreach (var std in inDbListStd)
            {
                var studentViewModel =  ConvertTypeHelper.ConvertServiceStudentToViewStudent(std);
                listStudent.Add(studentViewModel);
            }
            serviceClient.Close();
            return View(listStudent);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(StudentViewModel student)
        {
            if (ModelState.IsValid)
            {
                ServiceClient client = new ServiceClient();
                //convert to servive student

                var inDatabaseStudent = ConvertTypeHelper.ConvertViewStudentToServiceStudent(student);
                var res = client.CreateStudent(inDatabaseStudent);
                if (res != null)
                {
                    return RedirectToAction("Index");
                }
                client.Close();
            }
            return View(student);

        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            ServiceClient client = new ServiceClient();
            var serviceStd = client.GetStudentById(id);
            var viewStd = ConvertTypeHelper.ConvertServiceStudentToViewStudent(serviceStd);
            if(viewStd == null)
            {
                return RedirectToAction("Index");
            }
            return View(viewStd);
        }
        [HttpPost]
        public ActionResult Edit(StudentViewModel student)
        {
            if(ModelState.IsValid)
            {
                ServiceClient client = new ServiceClient();
                client.UpdateStudent(student.Id, ConvertTypeHelper.ConvertViewStudentToServiceStudent(student));
                client.Close();
                return RedirectToAction("Index");
                
            }
            return View(student);
        }

        public ActionResult Delete(int id)
        {
            ServiceClient client = new ServiceClient();
            client.DeleteStudent(id);
            client.Close();
            return RedirectToAction("Index");
        }
    }
}

ASM-WCF/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ASM-WCF/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ASM-WCF/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ASM-WCF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ASM-WCF/Views/Student/Create.cshtml
@model ASM_WCF.Models.StudentViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>StudentViewModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.RolleNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RolleNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RolleNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Birthday, new { @class ="form-control", type ="date"})
            @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.RadioButtonFor(model => model.Genre, 1, new { id = "male" })
            @Html.Label("male", "Nam")
            @Html.RadioButtonFor(model => model.Genre, 0, new { id = "female" })
            @Html.Label("female", "Nữ")

            @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Introduction, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Introduction, new { @class = "form-control", style = "height: 100px"})
            @Html.ValidationMessageFor(model => model.Introduction, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Tạo mới sinh viên" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ASM-WCF/Views/Student/Edit.cshtml
@model ASM_WCF.Models.StudentViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Student", "POST"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>StudentViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RolleNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RolleNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RolleNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (Model.Genre == ASM_WCF.Models.StudentViewModel.StudentGenre.Male)
                {
                    @Html.RadioButtonFor(model => model.Genre, 1, new { id = "male", @checked = "true", style = "margin-right:5px" })
                    @Html.Label("male", "Nam", new { style = "margin-right: 20px" })
                    @Html.RadioButtonFor(model => model.Genre, 0, new { id = "female", style = "margin-right: 5px" })
                    @Html.Label("female", "Nữ")

                }
                else
                {
                    @Html.RadioButtonFor(model => model.Genre, 1, new { id = "male", style = "margin-right:5px" })
                    @Html.Label("male", "Nam", new { style = "margin-right: 20px" })
                    @Html.RadioButtonFor(model => model.Genre, 0, new { id = "female", style = "margin-right: 5px", @checked="true" })
                    @Html.Label("female", "Nữ")

                }
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Introduction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Introduction, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Introduction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu Thông tin" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ASM-WCF/Views/Student/Index.cshtml
@model IEnumerable<ASM_WCF.Models.StudentViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RolleNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birthday)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Introduction)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RolleNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Birthday)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Introduction)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { item.Id}) |
            @Html.ActionLink("Delete", "Delete", new { item.Id })
        </td>
    </tr>
}

</table>